lib/quasar/web/router.ex
defmodule Quasar.Web.Router do
  use Quasar.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :json_api do
    plug :accepts, ["json-api"]
    plug JaSerializer.ContentTypeNegotiation
    plug JaSerializer.Deserializer
  end

  pipeline :file_api do
    plug :accepts, ["json"]
  end

  pipeline :with_user do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Quasar.Web.Plug.CurrentUser
  end

  pipeline :protected_browser do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Guardian.Plug.EnsureAuthenticated, handler: Quasar.Web.SessionController
    plug Quasar.Web.Plug.CurrentUser
  end

  pipeline :protected_api do
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
    plug Guardian.Plug.EnsureAuthenticated, handler: Quasar.Web.SessionController
    plug Quasar.Web.Plug.CurrentUser
  end

  scope "/", Quasar.Web do
    pipe_through [ :browser, :with_user ]

    get "/", SiteController, :index
    post "/sessions", SessionController, :create
    delete "/sessions", SessionController, :delete
    resources "/passwords", PasswordController, except: [:index, :show, :delete], singleton: true
    resources "/registrations", RegistrationController, only: [:new, :create]
  end

  scope "/", Quasar.Web do
    pipe_through(if Application.get_env(:quasar, :transient_storage), do: [:browser], else: [ :browser, :protected_browser ])
    get "/app/*anything", SiteController, :app
  end

  scope "/api", Quasar.Web.Api.V1 do
    pipe_through [ :file_api, :protected_api ]
    resources "/uploads", UploadController, only: [:create]
  end

  scope "/api", Quasar.Web.Api.V1 do
    pipe_through [ :json_api, :protected_api ]

    post "/sessions", SessionController, :create
    delete "/sessions", SessionController, :delete
    get "/search", SearchController, :index
    resources "/pages", PageController, except: [:new, :edit] do
      resources "/revisions", RevisionController, only: [:index, :create, :delete]
    end
    resources "/users", UserController, only: [:update, :delete], singleton: true
  end
end

lib/quasar/web/controllers/site_controller.ex
defmodule Quasar.Web.SiteController do
  use Quasar.Web, :authenticated_controller

  def index(conn, _params, current_user, _claims) do
    transient = Application.get_env(:quasar, :transient_storage)
    if current_user || transient, do: redirect(conn, to: "/app"), else: render(conn, "index.html")
  end

  def app(conn, _params, _current_user, _claims) do
    render conn, "app.html"
  end
end

lib/quasar/web/views/site_view.ex
defmodule Quasar.Web.SiteView do
  use Quasar.Web, :view

  alias Quasar.Accounts.User

  def user_json(conn) do
    user = if Application.get_env(:quasar, :transient_storage),
      do: %{ settings: User.initial_settings() },
      else: Map.take(conn.assigns.current_user, [:id, :settings, :name, :email])
    Quasar.Web.Api.V1.UserView
    |> JaSerializer.format(user, conn)
    |> Poison.encode!
  end
end

lib/quasar/web/templates/site/app.html.eex
<div id='app' data-user="<%= user_json(@conn) %>"></div>
<div id='app-loading'>
  <div>
    <h4>Quasar</h4>
    <div class="spinner">
      <div class="rect1"></div>
      <div class="rect2"></div>
      <div class="rect3"></div>
      <div class="rect4"></div>
      <div class="rect5"></div>
    </div>
  </div>
</div>

lib/quasar/web/templates/site/index.html.eex
<div class='sessions new'>
  <main>
    <h1>Quasar</h1>

    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <p class="alert alert-success" role="alert"><%= get_flash(@conn, :ok) %></p>

    <%= form_for @conn, session_path(@conn, :create), [as: :user], fn f -> %>
      <input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>">

      <div class="field">
        <%= email_input f, :email, placeholder: "Email", required: true, class: "pt-input" %>
      </div>
      <div class="field">
        <%= password_input f, :password, placeholder: "Password", required: true, class: "pt-input"  %>
      </div>
      <button class='pt-button' type="submit">Sign in</button>

      <hr/>

      <%= if Application.get_env(:quasar, :allow_registration) do %>
        <a href='<%= registration_path(@conn, :new) %>'>Create Account</a>
      <%= end %>
      <a href='<%= password_path(@conn, :new) %>'>Forgot Password?</a>
    <%= end %>
  </main>
</div>